server:
  port: 8080

spring:
  application:
    name: activiti-gradle-demo
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.211.80.218:3306/activiti?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Wwangyong@202007

# 所有日志级别，可以用全类型限定某个类的日志级别
logging:
  level:
    root: info